[toolchain]

[features]
resolution = true
skip-lint = false
startup_wait = "100000"
[programs.localnet]
spl_staking_program = "H4U8V1qsvTkFYP1hs6P4s89fvuzmHKauYhJXPtQgngM8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 10000000 tests/**/*.ts"
